### ISSUE TITLE
Creating an e-commerce demo

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#134]

**Comment by bidoubiwa** [comment]
Just out of curiosity, which feature does the movie dataset not demonstrate?
I would think that the following are not really compatible with the dataset
- synonyms 
- Distinct attribute

But I'm curious of the other that might be not suited for this dataset

**Comment by CaroFG** [comment]
We were thinking of the distinct attribute one

**Comment by fharper** [comment]
I don't remember our discussion about it, but yeah, we wanted to have another great example.

**Comment by CaroFG** [comment]
I think the Discogs data suggested by @Kerollmops [here](https://github.com/meilisearch/devrel/issues/144#issuecomment-764868451) suits our needs perfectly

**Comment by CaroFG** [comment]
Review of the datasets proposed in [this article](https://lionbridge.ai/datasets/24-best-ecommerce-retail-datasets-for-machine-learning/). I've only reviewed the first 14, because the other are customer reviews and sales data, not really products.

| Fashion-MNIST                                           | Greyscale training images for Machine Learning (idx files)                                               |
|---------------------------------------------------------|----------------------------------------------------------------------------------------------------------|
| Innerwear Data from Victoria’s Secret and Others        | Underwear. Obsolete image URLs                                                                           |
| Electronic Products and pricing data                    | Products from many different websites, no description, <br>image URLs different sizes, quality or broken |
| Men's shoes                                             | A lot of duplicates. No colors to showcase distinct attribute                                            |
| Women's shoes                                           | A lot of duplicates. No colors to showcase distinct attribute                                            |
| Item data                                               | Unique values. Only 2 fields: id and description.                                                        |
| Fashion products on Amazon.com                          | Not fashion, but toys.                                                                                   |
| E-commerce tagging for clothing                         | Broken link                                                                                              |
| Online Retail Dataset (UCI Machine Learning Repository) | No picture, nor distinct attribute                                                                       |
| Brazilian E-Commerce Public Dataset                     | It's in portuguese. No picture.                                                                          |
| Online auctions dataset                                 | Auctions + 55% of the items are the same product.                                                        |
| Retailrocket Recommender System Dataset                 | Just numeric data                                                                                        |
| ECommerce Search Relevance                              | Data from e-bay, very heterogeneous. Missing product description.                                        |
| Best Buy Search Queries NER Dataset                     | Broken link                                                                                              |

**Comment by CaroFG** [comment]
Finding a suitable e-commerce dataset with images, that we can legally use has revealed itself to be quite tricky. Any help would be much appreciated 🙏

**Comment by fharper** [comment]
@CaroFG can you define what a perfect dataset should look like please? Which fields, images, copyright...

**Comment by CaroFG** [comment]
Ideally, the dataset should have the following characteristics: 

1. Free / open license so we can use the dataset
2. Several fields including : 
- a numerical one (to showcase the custom ranking rule and numeric filters)
- a long enough field like a "description" to showcase attributesToCrop
3. Some documents should only differ in one attribute value (size or color) to showcase the distinct attribute 
4. Good quality pictures
5. Several million documents

**Comment by bidoubiwa** [comment]
I'm just putting that here in case it might be a possibly dataset. Not sure at all. It's the UK website of oxfam:

> Oxfam is a confederation of 20 independent charitable organizations focusing on the alleviation of global poverty,

They have an online shop that uses this API: 
https://docs.oracle.com/en/cloud/saas/commerce-cloud/cxocc/op-ccstore-v1-search-get.html

I tried several routes and I got some results. It might be a bit tricky to fetch the data the way we want to so it might be not a good solution but so you know. 

Their website: https://onlineshop.oxfam.org.uk/

Example of usage of their public API: https://onlineshop.oxfam.org.uk/ccstoreui/v1/search

**Comment by shivaylamba** [comment]
We are building an e-commerce storefront demo to showcase the functionality of using Meilisearch in an e-commerce website. 

The following tech stack will be used for creating the demo : 
1. Frontend Storefront : [Medusa NextJS Storefront Starter](https://github.com/medusajs/nextjs-starter-medusa)
2. MedusaJS : [Headless E-Commerce Backend](https://github.com/medusajs/medusa)
3. TailwindCSS
4. Dataset: [Amazon Dataset](https://github.com/meilisearch/demo-amazon-dataset-export)(private link)

The following features will be showcased : 
1. Search for a particular

**Comment by shivaylamba** [comment]
The CSS has been updated for the demo.

**Comment by shivaylamba** [comment]
1. Currently creating another demo with smaller data showing capabilities of Medusa backend and creating a script to help map data such as price, tags, categories from Meilisearch to enable items such as filters, sorting etc. 

2. Started with the outline for a blog post.

**Comment by shivaylamba** [comment]
Update: 
1. Successfully created another demo with smaller data showing capabilities of Medusa backend and creating a script to help map data such as price, tags, categories from Meilisearch to enable items such as filters, sorting etc.

2. Updated the outline for the blog post with the new demo.

**Comment by shivaylamba** [comment]
Update: 
Demo in the final stages of getting live: Currently a PR has been created: https://github.com/meilisearch/demos/pull/65

**Comment by Strift** [comment]
Hello there,

It's been a while since we got an update on this issue. I've started working on a new ecommerce demo. ✨ 

## Context & Objectives

**Demo website**
Showcase how Meilisearch can be used to build an ecommerce website.

**Demo repository**
Offer a starting point or reference for how to implement Meilisearch for ecommerce with Nuxt 3

**Tutorial**
An article will also be created to complement to the other deliverables, and offer a more guided approach to the implementation.

🔗  (WIP) repository: [meilisearch/ecommerce-demo](https://github.com/meilisearch/ecommerce-demo )

## Current Progress

- Storybook for UI components (will be a good starting point for the tutorial)
- Meili instance with 1000 products (thanks to Shivay’s dataset)
- Features: search bar, facets filters, sorting, range slider, pagination
- Partial SSR support (disabled in the demo)

⚙️ **A note on SSR**

- It’s currently not fully working because I have to work around some vue-instantsearch features which lack docs (or my knowledge is limited)
- That being said, SSR is a **must have** for SEO, and thus for ecommerces—I am looking forward to updating this demo once we know how to handle that
- We met with @bidoubiwa to share what I learned about Nuxt / SSR. I hope it'll be useful to the integration team

🚀 **What's next?**

After a round of feedback on the demo, I will start working on the tutorial—the article counterpart that will go with this demo.

The current idea for it is:
- Explain the UI/UX choices based on what's important for ecommerce
- Start the coding part from the basis of a working repo: UI components are implement, but connection with db is missing

The tutorial would roughly follow these steps:
- Setup the Meilisearch instance 
- Plug things by implementing instant-meilisearch and a search bar (basic implementation)
- Dive deeper with ecommerce-relavant features: facets, sorting, pagination, etc

Cheers,

**Comment by shivaylamba** [comment]
Looking forward to seeing the new demo!

**Comment by shivaylamba** [comment]
super awesome!
