### ISSUE TITLE
Create a new version release process for the DevRel team

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#162]
Starting after v0.19, devrel will be responsible for the demos, which means, updating and testing them with new meilisearch version.

**Comment by fharper** [comment]
Would be nice to share what is the process you were using to do that @curquiza, if you have something written down. If not, it's fine :)

**Comment by curquiza** [comment]
Hum, so here is the current process: update the MeiliSearch version in all the DO pods.
How to update MeiliSearch? I use these commands: https://github.com/meilisearch/meilisearch-digitalocean/issues/50#issuecomment-653784438
Then I re-run the script to populate the MeiliSearch following the corresponding READMEs. Except for finding-pypi because this is too complex and too long so I wait for the cron job to pass.
⚠️ I haven't used the dumps for the moment, I think this could be a good idea to integrate them in the process, it would avoid re-running the scripts to re-populate MeiliSearch.
To know how many droplets we have, you can ask @eskombro. We planned to do a Notion page to list all the droplets that are accessible and which index is on which pod. I think we should definitely do it now 😇

**Comment by eskombro** [comment]
It would be indeed interesting to use `dumps` indeed, the indexing process of PyPI is just extremely long (it takes hours) and I'm guessing for the other demos too. There are two droplets containing the indexes, I'll list them on the Notion page and give you the credentials for full access!

**Comment by fharper** [comment]
Perfect, thanks to both of you.

**Comment by ferdi05** [comment]
[Process created](https://github.com/meilisearch/devrel/blob/main/process/release_process.md) by @CaroFG during Q3 2022
