### ISSUE TITLE
Blog post: how we use dependabot

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#219]
Idea from @curquiza while writing the tech standards for MeiliSearch

**Comment by fharper** [comment]
I didn't tag you @curquiza as I'm not sure if you wanted to write it.

**Comment by curquiza** [comment]
I'm not really sure we want to write an article about our usage of dependabot right now.
It does not fit exactly our needs in all situations, and I don't know yet if it's because we don't master dependabot or not. It would be better to explain how we manage our dependencies in all the situations 🙂 But that's not for now since we don't have a real solution for the moment.

PS: I've nuanced the paragraph about dependencies concerning dependabot after your comment in the tech standard, I don't know if you have seen it.

**Comment by fharper** [comment]
I misunderstood that... Sorry
![image](https://user-images.githubusercontent.com/1170989/109200191-4f91df80-776e-11eb-8520-9f219029c944.png)

**Comment by curquiza** [comment]
Oh sorry, I wanted to mean "an article about the dependencies management" but I failed my sentence 😂
