### ISSUE TITLE
Developer relation program presentation to the company

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#289]

**Comment by ferdi05** [comment]
Have a recorded presentation before next followup? Anyone free can attend, otherwise they'll have the recorded presentation

**Comment by ferdi05** [comment]
So this issue is actually a milestone :) I'm splitting it into a few new issues before closing this one:

The @meilisearch/devrel-team will do two presentations to the MeiliSearch team members:

1. Presentation 1: What is DevRel and how we do it at MeiliSearch
2. Presentation 2: A look at our Q4 initiatives

For Presentation 1, we could:

- draw [the framework of the Developer Journey](https://devrelbook.substack.com/p/the-developer-journey-map)
- sort all DevRel initiatives according to the steps in this journey (and make sure no initiative was forgotten)
- create some content about what is DevRel (and what is a Developer Advocate doing)
- give some info about how the scope of everyone in the DevRel team
- give some perspectives on our recruiting plan
- create some content about how every MeiliSearch team member is facing developers so is doing Devreloper Relations
- give a very few best practices (and we could create a longer list)

For Presentation 2, we could:
- show our project organization
- tell what initiatives are planned for Q4 (and side activities)
- elaborate on current activities

We may to update this list along the way. When needed, we wan create/update issues in the [project milestone](https://github.com/meilisearch/devrel/milestone/10).

**Comment by ferdi05** [comment]
Issues were created in the project milestone. Closing this one.
