### ISSUE TITLE
Evaluate and challenge DevRel metrics

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/devrel#293]

**Comment by ferdi05** [comment]
Check Correlation https://www.youtube.com/watch?v=I5uinqFfl7w

**Comment by ferdi05** [comment]
Articles:
- [Defining success and metrics in DevRel](https://www.devrelx.com/post/defining-success-and-metrics-in-devrel)

**Comment by ferdi05** [comment]
There's so much content out there, I feel like this is going to be though

**Comment by ferdi05** [comment]
![yrvcdbq2vg48z492aber](https://user-images.githubusercontent.com/2602288/147088244-6d6490fb-2e01-4854-8411-f0a0dbda1eaf.png)
This image is taken from the [Measuring Developer Relations](https://dev.to/dx/measuring-developer-relations-ie8). I finally found an article that encompasses my vision of KPIs.

As described in #326, there are many metrics that we can measure and it's hard to choose one North Star metric for DevRel. North Star metrics are for companies, not for teams.

Ultimately, DevRel's goal is to get more active users, so to measure the growth of this metric.
But this is not a KPI that DevRel can use as it stands because we're not the only team doing work that has an influence on this metric. It would not be fair to evaluate our performance relying on this sole indicator.

As explained in the article and in our [manifesto](https://github.com/meilisearch/devrel/blob/main/devrel.md#the-3cs) (even if it needs some rework), we're embracing the 3C's approach. (In the article, "Product" is our equivalent of "Code").
And I think that we need the equivalent of a North Star metric for each of these pillars of our initiatives.
This means one master KPI for _Community_, for _Content_, and for _Code/Product_, and other metrics that can be useful to track.

## Community

The main KPI is **community health**. This can be measured through community members' activity, the size of the community, the number of discussions... It's hard to define what is the precise metric to track, we should use a combination of all this. Orbit should help to provide this metric. And it's fortunate, we can't define community health by its size only, or the number of answered questions.

This metric should be created as part of #327.

Some other metrics that can be part of the Community dashboard:
- Number of Slack community members
- Number of Slack community members active in the last 30 days (active = sent/replied to a message/discussion, added emojis) 
- Number of messages and discussions
- Number of members in each Orbit
- Number of Champions (see #284)

Here we focus on Slack. We could argue that the community is also on GitHub, Stack Overflow... if needed these metrics will be assessed again.

##  Content

The main KPIs are **analytics on the Ressource Center**. The main current difficulty is this Ressource Center doesn't exist yet and [we haven't done much work about it](https://github.com/meilisearch/devrel/milestone/5).
In the meantime, we can rely on other metrics. 

Some other metrics that can be part of the Content dashboard:
- Number of UGC (blogposts, tutorials, ...)
- Number of events (meetups, conferences, ...) and attendance
- Number of workshops and attendance
- Number of newsletter subscribers, opens and clicks
- Number of Twitter followers, mentions, and engagement
- Number of Linkedin followers, mentions, and engagement
- Number of blog posts created and audience
- Number of demos created
- Number of use cases
- Domain authority

## Code/Procuct

The main KPI is the **number of downloads**. Distribution is key, and this measures if it's done right.

- Number of contributors
- Number of GitHub Stars
- Number of product improvement suggestions captured
- Number of integration users
- NPS/[Sean Ellis question](https://review.firstround.com/how-superhuman-built-an-engine-to-find-product-market-fit#anchoring-around-a-metric-a-leading-indicator-for-productmarket-fit)
- Number of reviews

**Comment by ferdi05** [comment]
That being said, it's time to add create dashboards on Amplitude :)

**Comment by qdequele** [comment]
Thanks @ferdi05. We can talk more about all the metrics that can be used and tracked later, but I wanted to give you my opinion on the main KPIs. 

**Community**
I also think that we could use the number of users per each orbit on Orbit as the main KPI. 

**Content**
I don't think the analytics on the Resource Center is the best indicator. I think we can have as a main KPI the total number of visitors on all `meilisearch.com` sites as a main KPI. This is related to our awareness. 

**Code/Product**
We use the number of unique users per month KPI for the product extensively. I think this is one of the most relevant metrics today from a product perspective along with the number of servers used in production.

**Comment by ferdi05** [comment]
Hi @qdequele, thanks for your quick reaction.
My thoughts are below:

> **Community** I also think that we could use the number of users per each orbit on Orbit as the main KPI.

I agree. We could start with this KPI and make `Presence` a side metric. `Presence` is the Sum of (love * reach) of each member of the whole community and for each orbit, as described in the [Orbit model KPIs](https://github.com/orbit-love/orbit-model#orbit-kpis).

> **Content** I don't think the analytics on the Resource Center is the best indicator. I think we can have as a main KPI the total number of visitors on all `meilisearch.com` sites as a main KPI. This is related to our awareness.

The Resource Center being part of our websites, focusing on all visitors of MeiliSearch's websites will give a broader picture. Let's keep tracking the Resource center analytics, as DevRel should largely own it, which is less the case for other MeiliSearch websites.

Quick question: By MeiliSear websites, do we agree that these sites are:
- the main website
- the blog
- the documentation website
- and possibly subdomains with our demos (like the [Crates demo](https://crates.meilisearch.com/)) ?

> **Code/Product** We use the number of unique users per month KPI for the product extensively. I think this is one of the most relevant metrics today from a product perspective along with the number of servers used in production.

I do agree that it is the metric to follow.
But as I said in my comment (see below), I feel like it's the North Star metric of everything we do at DevRel, that a few teams at MeiliSearch can influence independently of DevRel. 

> Ultimately, DevRel's goal is to get more active users, and we should measure this metric's growth.
> But this is not a KPI that DevRel can use as it stands because we're not the only team doing work that influences this metric. It would not be fair to rely on this sole indicator to evaluate our performance.

I think that the main `Code` metric could be `downloads` as it mirrors our acquisition, education, and distribution efforts.

I'll be happy to discuss this last item and everything else later.
I will edit my long comment with what we discussed here.

**Comment by ferdi05** [comment]
Rather than downloads, I thank that launches could be a better main metric for the Code pillar.

**Comment by ferdi05** [comment]
The most essential part of the content was [duplicated at the root of the repo](https://github.com/meilisearch/devrel/blob/main/metrics.md). Closing this issue.
