### ISSUE TITLE
Create an Issue template

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/devrel#309]
Some of our repos already have Issues templates, but it's not the case for all of them.

**Comment by CaroFG** [comment]
@curquiza could you confirm that all integrations already have an issue template?

**Comment by CaroFG** [comment]
On reflection, I wonder if an issue template is really needed, since the main repositories that users contribute to are already covered:

**Comment by curquiza** [comment]
> @curquiza could you confirm that all integrations already have an issue template?

Yes, we have an issue template in every repository.

I don't think a generic template issue is necessary since it can highly depend on the repo. Encouraging the missing repo to add a template is maybe a good thing to do

I would add the [mini-dashbord](https://github.com/meilisearch/mini-dashboard) repo might need a templating issue as well.

**Comment by ferdi05** [comment]
I think that we should check with the maintainers of repos without template if they think that they need a generic/custom/no template

**Comment by CaroFG** [comment]
Hi @dichotommy and @mdubus, in order to improve the contributors' experience, we would like all the repositories that may receive contributions to have an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). 

We considered adding a default one for all MeiliSearch repos. Since every repo has its particularities, we thought it would be better if the maintainers added one adapted to their requirements. WDTY?

**Comment by dichotommy** [comment]
Hello! 👋🏻 Looks like I'm getting to all of my missed DevRel notifications today. Lo siento 😔🙏🏻

On the docs repo, I believe that we have a generic PR template stemming from the organization, and no issue template at all.

If we add a specific template for PRs to the docs repo, will that override the generic organization-wide template? 🤔

If so, we may want to do it. I can only speak for myself, but I `cmd + a` + delete our current PR template almost every time I make one because it simply doesn't feel relevant to our repo. Specifically, asking all PRs to resolve an existing issue doesn't feel docs-friendly to me. I worry that it could discourage spontaneous small fixes, which while not exciting are still our most common type of contribution.

I also think that creating a documentation-specific issue template could be a great idea. What do you think @maryamsulemani97 @guimachiavelli ? What would a good issue template for the docs repo look like?

**Comment by CaroFG** [comment]
So the mini-dashboard has now an issue template.

**Comment by ferdi05** [comment]
maybe for the tokenizer repo cc @ManyTheFish

**Comment by curquiza** [comment]
> Do you think it's necessary to have an issue template on those repos @curquiza ?

Hum not sure this is necessary, people only open issues on meilisearch side so far, which is what we expect. If we start having "polluting" issues on Milli and Tokenizer, we will think about a template to redirect the contributors.
We are currently thinking about a better organization to get feedback for the Tokenizer with Many, but since it's a WIP (and not really a priority), this might change slowly and we don't know exactly what we want 🙂

I think the most important for these repos is to add a CONTRIBUTING. It's on my todo, but I did not prioritize it for the moment! Totally my fault!

**Comment by CaroFG** [comment]
I am closing this issue then. Please reopen it if you deem it necessary @ferdi05

**Comment by ferdi05** [comment]
thanks for your great work on this issue @CaroFG
