### ISSUE TITLE
Create a tutorial on words splitting for more extensive search

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#35]
There is no way out of the box to get search results for search terms not in the first position of a field.

As an example, if I have Honolulu in the database and someone search lulu, the result won't appear.

In that case, a word splitting job needs to be done while indexing the content. To do that, you can use a tool like [BPEmb](https://github.com/bheinzerling/bpemb).

It would be nice to write a tutorial on how to do that, and use this (or any other tool we find that can do the job easily).

The idea started from a [discussion](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1607528810416700) in our Slack Community.

**Comment by fharper** [comment]
@CaroFG maybe it's one you can write?

**Comment by CaroFG** [comment]
I discussed it with @tpayet  but he wasn't very fond of it...

**Comment by fharper** [comment]
We had one user who had to find how to do it, and another asking for help about this exact problem. For me, it's the most feedback so far for something people need.

Let's try to have those discussions here for transparency please 😀

@tpayet what were your points about not doing this?

**Comment by tpayet** [comment]
Hello, sorry for not answering earlier 😬 

MeiliSearch is designed for search-as-you-type and therefore is built towards prefix-search. This is not a particular constraint but it is one of the primary "philosophy" and feature, if I can say so, of the project.

When people ask about splitting words in order to index them and be able to search in the middle of any word I fear that we may not be clear enough about the usage of MeiliSearch. If we are going to write a tutorial right now about how to get around around a feature of MeiliSearch I am afraid that it might have the wrong message.

I was not fond of the idea of writing this kind of tutorial right now because maybe we have to make our message clearer about the usage of MeiliSearch and if people really need this kind of stuff, then maybe write about it but again this is not what MeiliSearch has been built for. When splitting words and sending the different ngrams into MeiliSearch, we are growing the index size and we kind of become a cheap alternative to Elasticsearch ^^

**Comment by fharper** [comment]
Sounds good to me! It's perfectly fine to tell people that it's not how they should use Meili since it wasn't built for that. I'm all for being true to what we do! I was missing the knowledge on why it wasn't a good idea, thanks for sharing.

PS: don't stressed out about the time to answer!
